import '../models/equipment.dart';
import '../models/user_model.dart';
import '../models/complaint.dart';
import '../models/notification_item.dart';

class MockData {
  static List<UserModel> getNurses() {
    final now = DateTime.now();
    return [
      UserModel(
        id: 'nurse-1',
        employeeId: 'NUR-1042',
        name: 'Elena Vance, RN',
        email: 'elena.vance@stjude-hospital.org',
        department: 'ICU - Intensive Care',
        roleTitle: 'Senior Staff Nurse',
        shift: 'Morning (07:00 - 15:00)',
        role: UserRole.nurse,
        pin: '1234',
        isActive: true,
        createdAt: now.subtract(const Duration(days: 120)),
      ),
      UserModel(
        id: 'nurse-2',
        employeeId: 'NUR-2089',
        name: 'Marcus Reed, BSN',
        email: 'marcus.reed@stjude-hospital.org',
        department: 'Emergency Room (ER)',
        roleTitle: 'Triage Nurse Specialist',
        shift: 'Evening (15:00 - 23:00)',
        role: UserRole.nurse,
        pin: '1234',
        isActive: true,
        createdAt: now.subtract(const Duration(days: 90)),
      ),
      UserModel(
        id: 'nurse-3',
        employeeId: 'NUR-3015',
        name: 'Sarah Lin, RN',
        email: 'sarah.lin@stjude-hospital.org',
        department: 'Pediatric Care Unit',
        roleTitle: 'Pediatric Charge Nurse',
        shift: 'Night (23:00 - 07:00)',
        role: UserRole.nurse,
        pin: '1234',
        isActive: true,
        createdAt: now.subtract(const Duration(days: 60)),
      ),
      UserModel(
        id: 'nurse-4',
        employeeId: 'NUR-4022',
        name: 'David Kim, RN',
        email: 'david.kim@stjude-hospital.org',
        department: 'Cardiology & Cath Lab',
        roleTitle: 'Cardiac Care Nurse',
        shift: 'Morning (07:00 - 15:00)',
        role: UserRole.nurse,
        pin: '1234',
        isActive: true,
        createdAt: now.subtract(const Duration(days: 45)),
      ),
      UserModel(
        id: 'admin-1',
        employeeId: 'ADM-001',
        name: 'Dr. Arthur Pendelton',
        email: 'biomed.admin@stjude-hospital.org',
        department: 'BioMedical Engineering & Ops',
        roleTitle: 'BioMed Operations Director',
        shift: 'General (08:00 - 17:00)',
        role: UserRole.admin,
        pin: '9999',
        isActive: true,
        createdAt: now.subtract(const Duration(days: 365)),
      ),
    ];
  }

  static List<EquipmentModel> getEquipments() {
    final now = DateTime.now();
    return [
      EquipmentModel(
        id: 'eq-1',
        qrCode: 'EQ-VENT-101',
        name: 'Hamilton-G5 Mechanical Ventilator',
        category: 'Ventilators',
        modelNumber: 'HG5-2024-X',
        serialNumber: 'SN-VENT-99421',
        location: const EquipmentLocation(
          building: 'Main Tower',
          floor: '3rd Floor',
          department: 'ICU - Critical Care',
          room: '304-B',
          bedOrStation: 'Bed 4',
        ),
        availability: EquipmentAvailability.inUse,
        operationalStatus: OperationalStatus.optimal,
        maintenanceHealth: MaintenanceHealth.good,
        batteryLevel: 94,
        isWallPowered: true,
        isSanitized: true,
        lastMaintainedDate: now.subtract(const Duration(days: 14)),
        nextMaintenanceDate: now.add(const Duration(days: 76)),
        lastUpdatedTime: now.subtract(const Duration(minutes: 12)),
        lastUpdatedBy: 'Elena Vance (ICU)',
        currentAssignedPatient: 'Pt. Robinson (#9941)',
        notes: 'Equipped with IntelliVent-ASV module and high-flow nasal cannula kit.',
        manufacturer: 'Hamilton Medical AG',
      ),
      EquipmentModel(
        id: 'eq-2',
        qrCode: 'EQ-PUMP-204',
        name: 'BD Alaris Plus Infusion Pump',
        category: 'Infusion Pumps',
        modelNumber: 'Alaris-8100',
        serialNumber: 'SN-PMP-77210',
        location: const EquipmentLocation(
          building: 'Main Tower',
          floor: '3rd Floor',
          department: 'ICU - Critical Care',
          room: 'Storage Hub 3A',
          bedOrStation: 'Rack 2',
        ),
        availability: EquipmentAvailability.available,
        operationalStatus: OperationalStatus.optimal,
        maintenanceHealth: MaintenanceHealth.good,
        batteryLevel: 100,
        isWallPowered: false,
        isSanitized: true,
        lastMaintainedDate: now.subtract(const Duration(days: 30)),
        nextMaintenanceDate: now.add(const Duration(days: 60)),
        lastUpdatedTime: now.subtract(const Duration(minutes: 45)),
        lastUpdatedBy: 'BioMed Central',
        notes: 'Sanitized & calibrated. Guardrails safety software verified.',
        manufacturer: 'Becton Dickinson (BD)',
      ),
      EquipmentModel(
        id: 'eq-3',
        qrCode: 'EQ-DEFIB-007',
        name: 'Philips HeartStart MRx Defibrillator',
        category: 'Defibrillators',
        modelNumber: 'M3536A-ER',
        serialNumber: 'SN-DFB-33109',
        location: const EquipmentLocation(
          building: 'West Wing',
          floor: '1st Floor',
          department: 'Emergency Room (ER)',
          room: 'Crash Bay 1',
          bedOrStation: 'Cart A',
        ),
        availability: EquipmentAvailability.available,
        operationalStatus: OperationalStatus.optimal,
        maintenanceHealth: MaintenanceHealth.good,
        batteryLevel: 98,
        isWallPowered: false,
        isSanitized: true,
        lastMaintainedDate: now.subtract(const Duration(days: 7)),
        nextMaintenanceDate: now.add(const Duration(days: 83)),
        lastUpdatedTime: now.subtract(const Duration(minutes: 5)),
        lastUpdatedBy: 'Marcus Reed (ER)',
        notes: 'Adult & pediatric pads inspected. Daily self-test passed.',
        manufacturer: 'Philips Healthcare',
      ),
      EquipmentModel(
        id: 'eq-4',
        qrCode: 'EQ-MON-309',
        name: 'GE Carescape B850 Patient Monitor',
        category: 'Patient Monitors',
        modelNumber: 'CS-B850-V3',
        serialNumber: 'SN-MON-88123',
        location: const EquipmentLocation(
          building: 'Main Tower',
          floor: '4th Floor',
          department: 'Cardiology & Cath Lab',
          room: 'Room 412',
          bedOrStation: 'Station 1',
        ),
        availability: EquipmentAvailability.underMaintenance,
        operationalStatus: OperationalStatus.minorIssue,
        maintenanceHealth: MaintenanceHealth.underRepair,
        batteryLevel: 45,
        isWallPowered: true,
        isSanitized: false,
        lastMaintainedDate: now.subtract(const Duration(days: 45)),
        nextMaintenanceDate: now.add(const Duration(days: 5)),
        lastUpdatedTime: now.subtract(const Duration(hours: 3)),
        lastUpdatedBy: 'Tech Jackson (BioMed)',
        notes: 'NIBP pressure cuff transducer calibration in progress.',
        manufacturer: 'GE HealthCare',
      ),
      EquipmentModel(
        id: 'eq-5',
        qrCode: 'EQ-PUMP-209',
        name: 'Baxter Sigma Spectrum Infusion Pump',
        category: 'Infusion Pumps',
        modelNumber: 'Spectrum-V8',
        serialNumber: 'SN-PMP-44581',
        location: const EquipmentLocation(
          building: 'Pediatric Pavilion',
          floor: '2nd Floor',
          department: 'Pediatric Care Unit',
          room: 'Room 205',
          bedOrStation: 'Bed 2',
        ),
        availability: EquipmentAvailability.missing,
        operationalStatus: OperationalStatus.minorIssue,
        maintenanceHealth: MaintenanceHealth.routineDueSoon,
        batteryLevel: null,
        isWallPowered: false,
        isSanitized: false,
        lastMaintainedDate: now.subtract(const Duration(days: 60)),
        nextMaintenanceDate: now.subtract(const Duration(days: 2)),
        lastUpdatedTime: now.subtract(const Duration(hours: 18)),
        lastUpdatedBy: 'Sarah Lin (Pediatrics)',
        notes: 'Reported missing during morning inventory audit. Not found in Clean Utility Room.',
        manufacturer: 'Baxter International',
      ),
      EquipmentModel(
        id: 'eq-6',
        qrCode: 'EQ-ECG-502',
        name: 'Mindray BeneHeart R12 Diagnostic ECG',
        category: 'ECG Machines',
        modelNumber: 'BH-R12',
        serialNumber: 'SN-ECG-11983',
        location: const EquipmentLocation(
          building: 'Main Tower',
          floor: '2nd Floor',
          department: 'General Ward - East',
          room: 'Nurse Station 2B',
          bedOrStation: 'Mobile Stand 3',
        ),
        availability: EquipmentAvailability.available,
        operationalStatus: OperationalStatus.optimal,
        maintenanceHealth: MaintenanceHealth.good,
        batteryLevel: 88,
        isWallPowered: false,
        isSanitized: true,
        lastMaintainedDate: now.subtract(const Duration(days: 20)),
        nextMaintenanceDate: now.add(const Duration(days: 70)),
        lastUpdatedTime: now.subtract(const Duration(minutes: 50)),
        lastUpdatedBy: 'Nurse Clara (East Ward)',
        notes: '12-lead thermal printer paper refilled.',
        manufacturer: 'Mindray Medical',
      ),
      EquipmentModel(
        id: 'eq-7',
        qrCode: 'EQ-USONIC-801',
        name: 'FUJIFILM Sonosite Edge II Ultrasound',
        category: 'Ultrasound',
        modelNumber: 'Edge-II-POC',
        serialNumber: 'SN-USN-66120',
        location: const EquipmentLocation(
          building: 'West Wing',
          floor: '1st Floor',
          department: 'Emergency Room (ER)',
          room: 'Trauma Bay 2',
          bedOrStation: 'Cart 1',
        ),
        availability: EquipmentAvailability.reserved,
        operationalStatus: OperationalStatus.optimal,
        maintenanceHealth: MaintenanceHealth.good,
        batteryLevel: 75,
        isWallPowered: false,
        isSanitized: true,
        lastMaintainedDate: now.subtract(const Duration(days: 10)),
        nextMaintenanceDate: now.add(const Duration(days: 80)),
        lastUpdatedTime: now.subtract(const Duration(minutes: 25)),
        lastUpdatedBy: 'Dr. Chang (ER)',
        notes: 'Reserved for incoming trauma team FAST exam.',
        manufacturer: 'FUJIFILM Sonosite',
      ),
      EquipmentModel(
        id: 'eq-8',
        qrCode: 'EQ-DIAL-401',
        name: 'Fresenius 2008T Hemodialysis System',
        category: 'Dialysis',
        modelNumber: 'FMC-2008T',
        serialNumber: 'SN-DIA-90412',
        location: const EquipmentLocation(
          building: 'South Pavilion',
          floor: '3rd Floor',
          department: 'Nephrology & Dialysis',
          room: 'Station 04',
          bedOrStation: 'Bay 4',
        ),
        availability: EquipmentAvailability.inUse,
        operationalStatus: OperationalStatus.optimal,
        maintenanceHealth: MaintenanceHealth.good,
        batteryLevel: null,
        isWallPowered: true,
        isSanitized: true,
        lastMaintainedDate: now.subtract(const Duration(days: 5)),
        nextMaintenanceDate: now.add(const Duration(days: 25)),
        lastUpdatedTime: now.subtract(const Duration(hours: 1)),
        lastUpdatedBy: 'Nurse Miller (Nephrology)',
        currentAssignedPatient: 'Pt. Alvarez (#4402)',
        notes: 'Bicarbonate and acid concentrate line test successful.',
        manufacturer: 'Fresenius Medical Care',
      ),
      EquipmentModel(
        id: 'eq-9',
        qrCode: 'EQ-SUCT-105',
        name: 'Medela Dominant Flex Portable Suction',
        category: 'Suction Units',
        modelNumber: 'DOM-FLEX-230',
        serialNumber: 'SN-SUC-55201',
        location: const EquipmentLocation(
          building: 'Main Tower',
          floor: '3rd Floor',
          department: 'ICU - Critical Care',
          room: 'Room 308-A',
          bedOrStation: 'Mobile Stand',
        ),
        availability: EquipmentAvailability.outOfService,
        operationalStatus: OperationalStatus.criticalError,
        maintenanceHealth: MaintenanceHealth.calibrationOverdue,
        batteryLevel: 10,
        isWallPowered: true,
        isSanitized: false,
        lastMaintainedDate: now.subtract(const Duration(days: 110)),
        nextMaintenanceDate: now.subtract(const Duration(days: 20)),
        lastUpdatedTime: now.subtract(const Duration(days: 1)),
        lastUpdatedBy: 'Tech Adams (BioMed)',
        notes: 'Vacuum leak detected in internal regulator. Awaiting spare diaphragm.',
        manufacturer: 'Medela Healthcare',
      ),
    ];
  }

  static List<ComplaintModel> getComplaints() {
    final now = DateTime.now();
    return [
      ComplaintModel(
        id: 'cmp-1',
        ticketNumber: 'CMP-8041',
        equipmentId: 'eq-5',
        equipmentName: 'Baxter Sigma Spectrum Infusion Pump',
        equipmentCode: 'EQ-PUMP-209',
        equipmentCategory: 'Infusion Pumps',
        type: ComplaintType.missingEquipment,
        severity: ComplaintSeverity.high,
        status: ComplaintStatus.inProgress,
        nurseId: 'nurse-3',
        nurseName: 'Sarah Lin, RN',
        nurseDepartment: 'Pediatric Care Unit',
        reportedLocation: 'Pediatric Ward 2nd Floor, Room 205',
        description: 'Pump was scheduled for Patient in Bed 2, but could not be located in designated room or utility closet.',
        errorCode: null,
        reportedAt: now.subtract(const Duration(hours: 18)),
        lastUpdatedAt: now.subtract(const Duration(hours: 2)),
        assignedTechName: 'Officer Miller (Security Ops)',
        resolutionSummary: null,
        timeline: [
          ComplaintTimelineEvent(
            title: 'Report Submitted',
            description: 'Nurse Sarah Lin logged missing equipment report.',
            timestamp: now.subtract(const Duration(hours: 18)),
            actorName: 'Sarah Lin, RN',
            actorRole: 'Pediatric Charge Nurse',
          ),
          ComplaintTimelineEvent(
            title: 'Under BioMed Review',
            description: 'Incident verified against hospital RFID zone logs.',
            timestamp: now.subtract(const Duration(hours: 14)),
            actorName: 'Dr. Arthur Pendelton',
            actorRole: 'BioMed Director',
          ),
          ComplaintTimelineEvent(
            title: 'Security RFID Search Assigned',
            description: 'RFID gateway pinged last known tag near Elevator 4.',
            timestamp: now.subtract(const Duration(hours: 2)),
            actorName: 'Officer Miller',
            actorRole: 'Security Ops',
          ),
        ],
      ),
      ComplaintModel(
        id: 'cmp-2',
        ticketNumber: 'CMP-7992',
        equipmentId: 'eq-4',
        equipmentName: 'GE Carescape B850 Patient Monitor',
        equipmentCode: 'EQ-MON-309',
        equipmentCategory: 'Patient Monitors',
        type: ComplaintType.equipmentProblem,
        severity: ComplaintSeverity.medium,
        status: ComplaintStatus.assignedToTech,
        nurseId: 'nurse-1',
        nurseName: 'Elena Vance, RN',
        nurseDepartment: 'ICU - Intensive Care',
        reportedLocation: 'Main Tower 4th Floor, Room 412',
        description: 'NIBP pressure cuff fails to calibrate and throws Error Code E-402 on inflation.',
        errorCode: 'E-402 (Pressure Leak)',
        reportedAt: now.subtract(const Duration(hours: 6)),
        lastUpdatedAt: now.subtract(const Duration(hours: 3)),
        assignedTechName: 'Tech Jackson (BioMed)',
        resolutionSummary: null,
        timeline: [
          ComplaintTimelineEvent(
            title: 'Complaint Logged',
            description: 'Reported by Elena Vance with error code E-402.',
            timestamp: now.subtract(const Duration(hours: 6)),
            actorName: 'Elena Vance, RN',
            actorRole: 'Senior Staff Nurse',
          ),
          ComplaintTimelineEvent(
            title: 'Technician Dispatched',
            description: 'Tech Jackson assigned to inspect sensor transducer in Room 412.',
            timestamp: now.subtract(const Duration(hours: 3)),
            actorName: 'Tech Jackson',
            actorRole: 'BioMed Technician',
          ),
        ],
      ),
      ComplaintModel(
        id: 'cmp-3',
        ticketNumber: 'CMP-7850',
        equipmentId: 'eq-2',
        equipmentName: 'BD Alaris Plus Infusion Pump',
        equipmentCode: 'EQ-PUMP-204',
        equipmentCategory: 'Infusion Pumps',
        type: ComplaintType.unavailableEquipment,
        severity: ComplaintSeverity.low,
        status: ComplaintStatus.resolved,
        nurseId: 'nurse-1',
        nurseName: 'Elena Vance, RN',
        nurseDepartment: 'ICU - Intensive Care',
        reportedLocation: 'Storage Hub 3A',
        description: 'Power cord was locked inside accessory locker without key.',
        errorCode: null,
        reportedAt: now.subtract(const Duration(days: 2)),
        lastUpdatedAt: now.subtract(const Duration(days: 1)),
        assignedTechName: 'Supervisor Hayes',
        resolutionSummary: 'Accessory drawer unlocked and backup AC cables stocked.',
        timeline: [
          ComplaintTimelineEvent(
            title: 'Report Submitted',
            description: 'Reported unavailable due to locked accessory cord.',
            timestamp: now.subtract(const Duration(days: 2)),
            actorName: 'Elena Vance, RN',
            actorRole: 'Senior Staff Nurse',
          ),
          ComplaintTimelineEvent(
            title: 'Resolved & Restocked',
            description: 'Locker opened and 4 standard IEC medical power cables replenished.',
            timestamp: now.subtract(const Duration(days: 1)),
            actorName: 'Supervisor Hayes',
            actorRole: 'BioMed Facilities',
          ),
        ],
      ),
    ];
  }

  static List<NotificationItem> getNotifications() {
    final now = DateTime.now();
    return [
      NotificationItem(
        id: 'notif-1',
        title: 'Ticket #CMP-7992 Assigned',
        message: 'BioMed Technician Jackson has been dispatched for GE Carescape Monitor (#EQ-MON-309).',
        type: NotificationType.complaintUpdate,
        timestamp: now.subtract(const Duration(hours: 3)),
        isRead: false,
        relatedComplaintId: 'cmp-2',
        relatedEquipmentId: 'eq-4',
      ),
      NotificationItem(
        id: 'notif-2',
        title: 'Equipment Sanitized & Available',
        message: 'BD Alaris Plus Infusion Pump (#EQ-PUMP-204) in Storage Hub 3A is now certified available.',
        type: NotificationType.equipmentStatusChange,
        timestamp: now.subtract(const Duration(minutes: 45)),
        isRead: false,
        relatedEquipmentId: 'eq-2',
      ),
      NotificationItem(
        id: 'notif-3',
        title: 'BioMed Scheduled Maintenance',
        message: 'Routine calibration for ICU Ventilators is scheduled for tomorrow at 06:00 AM.',
        type: NotificationType.maintenanceAlert,
        timestamp: now.subtract(const Duration(hours: 8)),
        isRead: true,
      ),
      NotificationItem(
        id: 'notif-4',
        title: 'Ticket #CMP-7850 Resolved',
        message: 'Complaint for BD Alaris Pump was resolved by Supervisor Hayes.',
        type: NotificationType.complaintUpdate,
        timestamp: now.subtract(const Duration(days: 1)),
        isRead: true,
        relatedComplaintId: 'cmp-3',
      ),
    ];
  }
}
